
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankur
 */
public class Add_Dealer extends javax.swing.JFrame {

    /**
     * Creates new form Dealer
     */
     
 public Add_Dealer() {
        initComponents();
        
        jTextField1.setText(logics.Root_Work.getLastRootID()+1+"");
        
        ResultSet rs=logics.Product_list.getproductlist();
        jComboBox2.removeAllItems();;
        try 
        {
         while(rs.next())
         {
             jComboBox2.addItem(rs.getString("Product_name"));
         }
        }
        catch (Exception e) 
        {
            
        }
        
 }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel1.setText("Dealer ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 150, 30);

        jLabel2.setText("First Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 180, 30);

        jLabel3.setText("Last Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 140, 180, 30);

        jLabel4.setText("Gender");
        jLabel4.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 190, 170, 30);

        jLabel5.setText("Address");
        jLabel5.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 230, 170, 30);

        jLabel6.setText("Phone Number");
        jLabel6.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 280, 150, 30);

        jLabel7.setText("Pincode");
        jLabel7.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 370, 200, 30);

        jLabel8.setText("Product");
        jLabel8.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 420, 200, 30);

        jLabel10.setText("Other Number");
        jLabel10.setPreferredSize(new java.awt.Dimension(75, 14));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 330, 140, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(250, 190, 140, 20);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(250, 270, 70, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 520, 110, 23);

        jLabel9.setText("Aadhar no.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 460, 120, 40);

        jTextField1.setEditable(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(75, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 40, 180, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 90, 180, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 140, 180, 30);

        jTextField4.setPreferredSize(new java.awt.Dimension(75, 30));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(250, 230, 180, 30);

        jTextField5.setPreferredSize(new java.awt.Dimension(75, 30));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(340, 270, 180, 30);

        jTextField6.setPreferredSize(new java.awt.Dimension(75, 20));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(250, 320, 180, 30);

        jTextField7.setPreferredSize(new java.awt.Dimension(75, 20));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(250, 370, 180, 30);

        jTextField8.setPreferredSize(new java.awt.Dimension(75, 30));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(250, 460, 180, 30);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(260, 410, 160, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                 
        try
            {    String id=jTextField1.getText();
                 String dealer_name_first=jTextField2.getText();
                 String dealer_name_last=jTextField3.getText();
                 String gender=String.valueOf(jComboBox1.getSelectedItem());
                 String dealer_addree=jTextField4.getText(); 
                 String dealer_phone_code=String.valueOf(jSpinner1.getValue());
                 String dealer_phone_no=jTextField5.getText();
                 String dealer_other_no=jTextField6.getText();
                 String dealer_pincode=jTextField7.getText();
                 String dealer_product=String.valueOf(jComboBox2.getSelectedItem());
                 String aadhar=jTextField8.getText();
                 Connection com = logics.DB_Work.myDBInstance();
                 PreparedStatement pstmt = com.prepareStatement("insert into dealer (`dealer_id`,`dealer_name_first`,`dealer_name_last`,`dealer_gender`,`dealer_address`,`dealer_phone_code`,`dealer_phone_no`,`dealer_pin_code`,`dealer_poducts`,`dealer_other_contact_no`,`aadhar_no`) values(?,?,?,?,?,?,?,?,?,?,?)");
                 pstmt.setString(1,id);
                 pstmt.setString(2,dealer_name_first);
                 pstmt.setString(3,dealer_name_last);
                 pstmt.setString(4,gender);
                 pstmt.setString(5,dealer_addree);
                 pstmt.setString(6,dealer_phone_code);
                 pstmt.setString(7,dealer_phone_no);
                 pstmt.setString(8,dealer_pincode);
                 pstmt.setString(9,dealer_product);
                 pstmt.setString(10,dealer_other_no);
                 pstmt.setString(11,aadhar);
                 int flag=pstmt.executeUpdate();    
            if(flag>0)
            {
                JOptionPane.showMessageDialog(null,"save");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"NOT save");
            }
        }
        catch(Exception e)
                {  JOptionPane.showMessageDialog(null, "not login" + e);}
                 
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

         
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Dealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
