
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankur
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        ResultSet rs=logics.Bill_stock.getproductlist();
        jComboBox1.removeAllItems();;
        try 
            {
             while(rs.next())
             {
                 jComboBox1.addItem(rs.getString("product"));
             }
            }
        catch(Exception e)
        {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 491));
        getContentPane().setLayout(null);

        jLabel1.setText("Product");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 70, 14);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 110, 80, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(440, 110, 130, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 200, 570, 260);

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 110, 51, 23);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 50, 110, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 50, 240, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(420, 50, 110, 30);

        jLabel2.setText("Date of Bill");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(580, 20, 110, 30);

        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 10, 110, 30);

        jLabel4.setText("Customer address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 10, 110, 30);

        jLabel5.setText("Customer Phone no.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 20, 120, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 140, 59, 30);

        jLabel6.setText("Available Quantity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 140, 90, 14);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 170, 70, 30);

        jLabel7.setText("Rate");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 170, 90, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(570, 60, 110, 20);

        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 110, 70, 14);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String product = jComboBox1.getSelectedItem().toString();
            String quantity=jTextField1.getText();
            String c_name=jTextField2.getText(); 
            String c_address=jTextField3.getText(); 
            String c_number=jTextField4.getText();
            Date date = jDateChooser1.getDate();
            String dob = DateFormat.getDateInstance().format(date);
            DateFormat df = new SimpleDateFormat("DD/MM/YYYY");
            String rate=jTextField6.getText();
            Connection com = logics.DB_Work.myDBInstance();
            PreparedStatement pstmt = com.prepareStatement("insert into bill (`product`,`quantity`,`c_name`,`c_address`,`c_number`,`c_date`,`rate`)value(?,?,?,?,?,?,?)");
            pstmt.setString(1, product);
            pstmt.setString(2,quantity);
            pstmt.setString(3,c_name);
            pstmt.setString(4,c_address);
            pstmt.setString(5,c_number);
            pstmt.setString(6,dob);
            pstmt.setString(7,rate);
            
            
            int flag = pstmt.executeUpdate();
            if (flag > 0) 
            {
                JOptionPane.showMessageDialog(this, "Added");
                func();
            }
            else 
            {
                JOptionPane.showMessageDialog(this, "Not Added");
            }          
        }   
        catch(Exception e)
        {System.out.println("---ERROR---a"+e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    
     try{   
            String product=String.valueOf(jComboBox1.getSelectedItem());
            Connection com = logics.DB_Work.myDBInstance();
            PreparedStatement pstmt = com.prepareStatement("select * from main_stock where `product`=? ");
            pstmt.setString(1, product); 
            ResultSet rs = pstmt.executeQuery();         
                while(rs.next())
                { 
                    String quantity=rs.getString("quantity");
                    String rate=rs.getString("rate");
                    jTextField5.setText(quantity);
                    jTextField6.setText(rate);
                }
     }
     catch(Exception e)
     {
     } 
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        

// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    public void func()
    {
        try
        {
            Connection com = logics.DB_Work.myDBInstance();
            PreparedStatement pstmt = com.prepareStatement("SELECT * FROM bill where c_number=?");
            pstmt.setString(1, jTextField4.getText().toString());
            
            ResultSet rs = pstmt.executeQuery();
            
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }   
        catch(Exception e)
        {
            System.out.println("---ERROR---a"+e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
