
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankur
 */
public class Rate_setter extends javax.swing.JFrame {

    /**
     * Creates new form Rate_setter
     */
    public Rate_setter() {
        initComponents();
        ResultSet rs=logics.Product_list.getproductlist();
        jComboBox1.removeAllItems();;
        try 
            {
             while(rs.next())
             {
                 jComboBox1.addItem(rs.getString("Product_name"));
             }
            }
        catch(Exception e)
        {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(677, 462));
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 60, 168, 30);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 170, 230, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 240, 170, 30);

        jLabel1.setText("Quatity");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 120, 90, 30);

        jLabel2.setText("Rate/Quantity");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 240, 100, 30);

        jLabel3.setText("Product ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 70, 90, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 370, 170, 23);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 60, 130, 30);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(210, 120, 130, 30);

        jLabel4.setText("Total Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 180, 130, 14);

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 300, 170, 40);

        jLabel6.setText("Sell Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 300, 90, 40);

        jLabel7.setText("quantity from defferent dealer");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 120, 260, 30);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 320, 110, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String product=String.valueOf(jComboBox1.getSelectedItem());
        jComboBox2.removeAllItems();
        int q1=0;
        try{   
              
               Connection com = logics.DB_Work.myDBInstance();
               PreparedStatement pstmt = com.prepareStatement("select * from stock where `product`=? ");
               pstmt.setString(1, product); 
               ResultSet rs = pstmt.executeQuery();  
               int total_quantity=0;
                   while(rs.next())
                   { 
                       String quantity=rs.getString("quantity");
                       jComboBox2.addItem(quantity);                  
                       total_quantity=Integer.parseInt(quantity);
                       q1=q1+total_quantity;
                    }
                String a = Integer.toString(q1);
                jTextField2.setText(a); 
            }
        catch(Exception e)
        {
        }      

    jTextField1.setText(product);

     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
    // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
      // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
//    String q=jTextField2.getText();
//    String total_quantity= jTextField3.getText();
    int quantity=Integer.parseInt(jTextField2.getText());    
    int total_quantity=Integer.parseInt(jTextField3.getText());
    jTextField4.setText(""+quantity*total_quantity);
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try
        {
            String product1=jTextField1.getText();
            Connection com = logics.DB_Work.myDBInstance();
                PreparedStatement pstmt = com.prepareStatement("select * from main_stock where `product`=?");
                pstmt.setString(1, product1);
                ResultSet rs=pstmt.executeQuery();
                        if(rs.next())
                        {
                            JOptionPane.showMessageDialog(this,"Already Existed..!!!! go to Update");
                        }
                        else{
                                try{
                            String product=jTextField1.getText();
                            String quantity = jTextField2.getText();
                            String rate = jTextField3.getText();  
                            String total_amount= jTextField4.getText();
                           pstmt = com.prepareStatement("insert into main_stock (`product`,`quantity`,`rate`,`total_amount`) values(?,?,?,?)");
                            pstmt.setString(1,product);
                            pstmt.setString(2,quantity);
                            pstmt.setString(3,rate); 
                            pstmt.setString(4,total_amount);
                                int flag=pstmt.executeUpdate();    
                                if(flag>0)
                                {
                                    JOptionPane.showMessageDialog(null,"save");

                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null,"Not save");
                                }
                          }
                          catch(Exception e){System.err.println("Error "+e);}
                            }
      }
       catch(Exception e){}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        String product=jTextField1.getText();
        String quantity = jTextField2.getText();
        String rate = jTextField3.getText();  
        String total_amount= jTextField4.getText();
        Connection com = logics.DB_Work.myDBInstance();
       PreparedStatement pstmt = com.prepareStatement("update main_stock set `quantity`=? ,`rate`=? ,`total_amount`=? where product=?");
        pstmt.setString(1,quantity);
        pstmt.setString(2,rate); 
        pstmt.setString(3,total_amount);
        pstmt.setString(4,product);
        
            int flag=pstmt.executeUpdate();    
            if(flag>0)
            {
                JOptionPane.showMessageDialog(null,"save");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Not save");
            }
      }
      catch(Exception e){System.err.println("Error "+e);}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rate_setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rate_setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rate_setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rate_setter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rate_setter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
