
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankur
 */
public class Remove_Dealer extends javax.swing.JFrame {
private void clearTable()
    {       DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            while(dtm.getRowCount()>0)
                {   for(int i=0;i<dtm.getRowCount();i++)
                         {
                             dtm.removeRow(i);
                         }
                }
    }
    /**
     * Creates new form Remove_Dealer
     */
    public Remove_Dealer() {
        initComponents();
        ResultSet rs=logics.Dealer_name_list.getDealerList(); //fn from Dealer_Product_list from getDealer_ON_ProductName() for combo box 1
        jComboBox1.removeAllItems();
        try 
            {
             while(rs.next())
             {
                 jComboBox1.addItem(rs.getString("dealer_id"));
             }
            }
        catch (Exception e) 
             {                 }
         ResultSet rs1=logics.Dealer_Product_list.getDealerProductList();// show all dealer 
        try 
            {
                 jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
             }
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 437));
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(690, 20, 110, 30);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 70, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 20, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 1280, 530);

        jLabel1.setText("Show dealer details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 14, 120, 40);

        jLabel2.setText("Select id to delete dealer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 20, 160, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            String product=jTextField1.getText();
         Connection com = logics.DB_Work.myDBInstance();
          PreparedStatement pstmt = com.prepareStatement("delete from dealer where `dealer_id`=?");//delete from table1 where `id`=?
          pstmt.setString(1, product);
          clearTable();
          int flag=pstmt.executeUpdate();    
            if(flag>0)
            {
                JOptionPane.showMessageDialog(null,"Dealer is deleted");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Dealer is not deleted");
            }
        }   
        catch(Exception e)
        {System.out.println("---ERROR---"+e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
         
        String dealer_id=String.valueOf(jComboBox1.getSelectedItem());
        
        ResultSet rs=logics.Dealer_name_list.getDealer_ON_Dealerid(dealer_id);
        jTable1.removeAll();
        try 
            {
                 jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             }
        catch(Exception e){}     
// String dealer_name=String.valueOf(jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove_Dealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove_Dealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
